In [1]:
!pip install bertopic

Collecting bertopic
  Downloading bertopic-0.17.4-py3-none-any.whl.metadata (24 kB)
Requirement already satisfied: hdbscan>=0.8.29 in /usr/local/lib/python3.12/dist-packages (from bertopic) (0.8.40)
Requirement already satisfied: umap-learn>=0.5.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (0.5.9.post2)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (2.0.2)
Requirement already satisfied: pandas>=1.1.5 in /usr/local/lib/python3.12/dist-packages (from bertopic) (2.2.2)
Requirement already satisfied: plotly>=4.7.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (5.24.1)
Requirement already satisfied: scikit-learn>=1.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (1.6.1)
Requirement already satisfied: sentence-transformers>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from bertopic) (5.1.2)
Requirement already satisfied: tqdm>=4.41.1 in /usr/local/lib/python3.12/dist-packages (from bertopic) (4.67.1)
Requirement already satisfied: llvmlite>0.36.0 in /usr/local/lib/python3.12/dist-packages (from bertopic) (0.43.0)
Requirement already satisfied: scipy>=1.0 in /usr/local/lib/python3.12/dist-packages (from hdbscan>=0.8.29->bertopic) (1.16.3)
Requirement already satisfied: joblib>=1.0 in /usr/local/lib/python3.12/dist-packages (from hdbscan>=0.8.29->bertopic) (1.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.5->bertopic) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.5->bertopic) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.1.5->bertopic) (2025.2)
Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly>=4.7.0->bertopic) (9.1.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from plotly>=4.7.0->bertopic) (25.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.0->bertopic) (3.6.0)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.4.1->bertopic) (4.57.2)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.4.1->bertopic) (2.9.0+cu126)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.4.1->bertopic) (0.36.0)
Requirement already satisfied: Pillow in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.4.1->bertopic) (11.3.0)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers>=0.4.1->bertopic) (4.15.0)
Requirement already satisfied: numba>=0.51.2 in /usr/local/lib/python3.12/dist-packages (from umap-learn>=0.5.0->bertopic) (0.60.0)
Requirement already satisfied: pynndescent>=0.5 in /usr/local/lib/python3.12/dist-packages (from umap-learn>=0.5.0->bertopic) (0.5.13)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (3.20.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (2025.3.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (2.32.4)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (1.2.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.1.5->bertopic) (1.17.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.6)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.11.1.6)
Requirement already satisfied: triton==3.5.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.5.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers>=0.4.1->bertopic) (0.7.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers>=0.4.1->bertopic) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers>=0.4.1->bertopic) (2025.11.12)
Downloading bertopic-0.17.4-py3-none-any.whl (154 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.7/154.7 kB 6.8 MB/s eta 0:00:00
Installing collected packages: bertopic
Successfully installed bertopic-0.17.4

In [2]:
import re
from bertopic import BERTopic
from sentence_transformers import SentenceTransformer
from sklearn.feature_extraction.text import CountVectorizer
from umap import UMAP
from hdbscan import HDBSCAN
import pandas as pd

df = pd.read_csv("quran_sahih.csv")
docs = df["text"].astype(str).tolist()
  # ===============================
# 1. Preprocessing
# ===============================

def clean_text(doc):
    doc = str(doc).lower()

    doc = re.sub(r"[^a-zA-Z\s]", " ", doc)
    tokens = doc.split()
    return " ".join(tokens)

docs_clean = [clean_text(doc) for doc in docs]

# ===============================
# 2. STOPWORDS — USE ONLY ENGLISH
# ===============================
stop_words = [
    # Standard English stopwords
    "a","about","above","after","again","against","all","am","an","and","any","are",
    "as","at","be","because","been","before","being","below","between","both","but",
    "by","can","could","did","do","does","doing","down","during","each","few","for",
    "from","had","has","have","having","he","her","here","hers","herself","him",
    "himself","his","how","i","if","in","into","is","it","its","itself","just","me",
    "more","most","my","myself","no","nor","not","of","off","on","once","only","or",
    "other","our","ours","ourselves","out","over","own","same","she","should","so",
    "some","such","than","that","the","their","theirs","them","themselves","then",
    "there","these","they","this","those","through","to","too","under","until","up",
    "very","was","we","were","what","when","where","which","while","who","whom","why",
    "will","with","would","you","your","yours","yourself","yourselves","upon","is","o",

    # Sahih-specific
    "indeed","then","thus","so","such","among","amongst","because","as for","so that",
    "those who","thereby","therein","thereafter","thereof","thereon","whereby",
    "wherein","whereof","whereupon","whatever","whichever","whomever","whenever",
    "wherever","anyone","anything","everyone","everything","either","neither",
    "whether",

    # Quranic formulas
    "say","o","s"

    # Structural Quran translation particles
    ,"hereafter","thereafter","except",
    "lest"
]

# ===============================
# 3. VECTORIZER
# ===============================
vectorizer = CountVectorizer(
    stop_words=stop_words,
    lowercase=True,
    ngram_range=(1,2),   # unigram only
    min_df=2,
    max_df=0.80
)

# ===============================
# 4. UMAP
# ===============================
umap_model = UMAP(
    n_neighbors=50,
    n_components=15,
    min_dist=0.3,
    metric='cosine',
    random_state=42
)

# ===============================
# 5. HDBSCAN
# ===============================
hdbscan_model = HDBSCAN(
    min_cluster_size=5,
    min_samples=2,
    cluster_selection_method='leaf',
    metric='euclidean'
)

# ===============================
# 6. EMBEDDINGS – YOU MUST USE THIS
# ===============================
embedding_model = SentenceTransformer(
    "paraphrase-multilingual-mpnet-base-v2"
)

# ===============================
# 7. BERTopic
# ===============================
topic_model = BERTopic(
    embedding_model=embedding_model,
    vectorizer_model=vectorizer,
    umap_model=umap_model,
    hdbscan_model=hdbscan_model,
    nr_topics="auto"
)

topics, probs = topic_model.fit_transform(docs_clean)
topic_model.visualize_topics()

/usr/local/lib/python3.12/dist-packages/hdbscan/robust_single_linkage_.py:175: SyntaxWarning: invalid escape sequence '\{'
  $max \{ core_k(a), core_k(b), 1/\alpha d(a,b) \}$.

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/723 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/1.11G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/402 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [3]:
topic_model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,3472,-1_allah_people_us_said,"[allah, people, us, said, lord, one, come, day...",[because of that we decreed upon the children ...
1,0,828,0_allah_muhammad_earth_fear allah,"[allah, muhammad, earth, fear allah, wills, be...",[whatever is in the heavens and whatever is on...
2,1,123,1_merciful_might merciful_lord exalted_mercifu...,"[merciful, might merciful, lord exalted, merci...",[and indeed your lord he is the exalted in mig...
3,2,48,2_said lord_believing servants_day resurrected...,"[said lord, believing servants, day resurrecte...",[he said my lord make for me a sign he said yo...
4,3,40,3_pharaoh_pharaoh said_haman_go pharaoh,"[pharaoh, pharaoh said, haman, go pharaoh, hau...",[pharaoh said you believed moses before i gave...
...,...,...,...,...,...
169,168,5,168_mention later_favorable_favorable mention_...,"[mention later, favorable, favorable mention, ...",[and we left for him favorable mention among l...
170,169,5,169_name lord_exalt name_lord great_name,"[name lord, exalt name, lord great, name, exal...",[so exalt the name of your lord the most great...
171,170,5,170_given record_record_record right_hand,"[given record, record, record right, hand, rig...",[so as for he who is given his record in his r...
172,171,5,171_saving_feed_want_poor,"[saving, feed, want, poor, captive, spite love...",[and does not encourage the feeding of the poo...
173,172,5,172_calamity_striking calamity_striking_overwh...,"[calamity, striking calamity, striking, overwh...",[and what can make you know what is the striki...

In [4]:

new_topics = topic_model.reduce_outliers(documents = docs_clean, topics = topics, strategy="c-tf-idf")

# You MUST run this step to update the model's internal representations
topic_model.update_topics(docs_clean, topics = new_topics, vectorizer_model = vectorizer)

print("Outliers successfully reduced and reassigned using the c-TF-IDF strategy.")
print("\nUpdated Topic Information:")
# Check the count of the -1 topic to verify the reduction
(topic_model.get_topic_info())

2025-12-05 04:53:46,990 - BERTopic - WARNING: Using a custom list of topic assignments may lead to errors if topic reduction techniques are used afterwards. Make sure that manually assigning topics is the last step in the pipeline.Note that topic embeddings will also be created through weightedc-TF-IDF embeddings instead of centroid embeddings.

Outliers successfully reduced and reassigned using the c-TF-IDF strategy.

Updated Topic Information:

,Topic,Count,Name,Representation,Representative_Docs
0,-1,12,-1_coral_choose_diverse_alarmed,"[coral, choose, diverse, alarmed, distracted, ...",[because of that we decreed upon the children ...
1,0,1036,0_muhammad_messenger_wills_belongs,"[muhammad, messenger, wills, belongs, fear all...",[whatever is in the heavens and whatever is on...
2,1,160,1_merciful_merciful lord_lord exalted_might me...,"[merciful, merciful lord, lord exalted, might ...",[and indeed your lord he is the exalted in mig...
3,2,76,2_said lord_day resurrected_believing servants...,"[said lord, day resurrected, believing servant...",[he said my lord make for me a sign he said yo...
4,3,70,3_pharaoh_pharaoh said_people pharaoh_pharaoh ...,"[pharaoh, pharaoh said, people pharaoh, pharao...",[pharaoh said you believed moses before i gave...
...,...,...,...,...,...
169,168,9,168_later_generations_left_remaining,"[later, generations, left, remaining, mention,...",[and we left for him favorable mention among l...
170,169,23,169_exalt_name lord_name_exalt allah,"[exalt, name lord, name, exalt allah, lord gre...",[so exalt the name of your lord the most great...
171,170,22,170_record_hand_right hand_read,"[record, hand, right hand, read, right, drew, ...",[so as for he who is given his record in his r...
172,171,18,171_feed_want_feeding_poor,"[feed, want, feeding, poor, oaths, spite, feed...",[and does not encourage the feeding of the poo...
173,172,7,172_calamity_striking_striking calamity_overwh...,"[calamity, striking, striking calamity, overwh...",[and what can make you know what is the striki...

In [5]:
# Assuming you want to sub-cluster Topic 3
TARGET_TOPIC_ID = 0

# 1. Get the indices of all documents belonging to the target topic
target_indices = [i for i, topic_id in enumerate(topics) if topic_id == TARGET_TOPIC_ID]

# 2. Extract the documents for the sub-clustering
sub_cluster_docs = [docs_clean[i] for i in target_indices]

print(f"Number of documents in Topic {TARGET_TOPIC_ID}: {len(sub_cluster_docs)}")
# 1. Create a fresh BERTopic model instance
sub_topic_model = BERTopic(
    embedding_model=embedding_model,
    vectorizer_model=vectorizer,
    # Re-use your UMAP/HDBSCAN models or create new ones for tuning
    umap_model=umap_model,
    hdbscan_model=hdbscan_model,
    nr_topics="auto"
)

# 2. Fit and Transform the subset of documents
sub_topics, sub_probs = sub_topic_model.fit_transform(sub_cluster_docs)

Number of documents in Topic 0: 828

In [6]:
sub_topic_model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,249,-1_said_people_good_sent,"[said, people, good, sent, believe, muhammad, ...",[it is that of which allah gives good tidings ...
1,0,102,0_punishment_fire_disbelievers_believe,"[punishment, fire, disbelievers, believe, neve...",[those who disbelieved and averted others from...
2,1,61,1_merciful_forgiving_forgiving merciful_allah ...,"[merciful, forgiving, forgiving merciful, alla...",[except for those who repent after that and co...
3,2,48,2_believed_prayer_let_fear allah,"[believed, prayer, let, fear allah, fear, witn...",[o you who have believed be persistently stand...
4,3,45,3_quran_revealed_verses_book,"[quran, revealed, verses, book, muhammad, reve...",[alif lam ra this is a book which we have reve...
5,4,28,4_worship_besides allah_besides_worship besides,"[worship, besides allah, besides, worship besi...",[you only worship besides allah idols and you ...
6,5,20,5_created_allah created_creation_sky,"[created, allah created, creation, sky, earth,...",[have you not seen that allah created the heav...
7,6,19,6_messenger_notification_obey_clear notification,"[messenger, notification, obey, clear notifica...",[and obey allah and obey the messenger but if ...
8,7,16,7_hypocrites_messenger_believers_allah messenger,"[hypocrites, messenger, believers, allah messe...",[and there are those hypocrites who took for t...
9,8,15,8_said_mary_wife_said lord,"[said, mary, wife, said lord, mention, sought,...",[mention o muhammad when the wife of imran sai...
10,9,14,9_allah obey_obey_fear allah_fear,"[allah obey, obey, fear allah, fear, raise, ha...","[so fear allah and obey me, so fear allah and ..."
11,10,12,10_gardens_rivers flow_flow_rivers,"[gardens, rivers flow, flow, rivers, beneath r...",[indeed allah will admit those who believe and...
12,11,12,11_deity_allah deity_ever living_sovereign,"[deity, allah deity, ever living, sovereign, k...",[allah there is no deity except him the ever l...
13,12,11,12_straight_path_straight path_lord lord,"[straight, path, straight path, lord lord, lor...",[jesus said and indeed allah is my lord and yo...
14,13,10,13_reward_charity_spend_lord fear,"[reward, charity, spend, lord fear, spend weal...",[so allah gave them the reward of this world a...
15,14,10,14_servants allah_chosen_servants_attributed,"[servants allah, chosen, servants, attributed,...","[but not the chosen servants of allah, but not..."
16,15,10,15_heavens_heavens earth_belongs_praise,"[heavens, heavens earth, belongs, praise, eart...",[whatever is in the heavens and earth exalts a...
17,16,10,16_sky_light_rain_see,"[sky, light, rain, see, night, sends, rain sky...",[and in the alternation of night and day and i...
18,17,9,17_fears allah_fears_fear_fear allah,"[fears allah, fears, fear, fear allah, allah r...","[he who fears allah will be reminded, as for h..."
19,18,9,18_spend good_spend_poor_zakah,"[spend good, spend, poor, zakah, expenditures,...",[charity is for the poor who have been restric...
20,19,9,19_threw_test_matter_distress,"[threw, test, matter, distress, breasts, kille...",[and you did not kill them but it was allah wh...
21,20,9,20_allies_take_fight_perhaps,"[allies, take, fight, perhaps, affection, jews...",[so fight o muhammad in the cause of allah you...
22,21,9,21_allah resurrect_resurrect_day_gathered,"[allah resurrect, resurrect, day, gathered, ho...",[only those who hear will respond but the dead...
23,22,9,22_messengers_sent messengers_stories_already ...,"[messengers, sent messengers, stories, already...",[and we have already sent messengers before yo...
24,23,8,23_muhammad_remind_warner_favor,"[muhammad, remind, warner, favor, clear warner...","[so remind o muhammad you are only a reminder,..."
25,24,8,24_brother_sent brother_said fear_people worship,"[brother, sent brother, said fear, people wors...",[and to thamud we sent their brother salih he ...
26,25,7,25_lie_unjust_denies_one,"[lie, unjust, denies, one, wrongdoers, verses,...",[and who is more unjust than one who invents a...
27,26,7,26_grieve_concerning grieve_fear concerning_al...,"[grieve, concerning grieve, fear concerning, a...",[unquestionably for the allies of allah there ...
28,27,6,27_created_die_life_competent allah,"[created, die, life, competent allah, strength...",[allah is the one who created you from weaknes...
29,28,6,28_give_victory_prayer_away allah,"[give, victory, prayer, away allah, devoutly, ...",[and whoever of you devoutly obeys allah and h...
30,29,6,29_said_rely_enter_said people,"[said, rely, enter, said people, lord, argue c...",[he said o my people have you considered if i ...
31,30,6,30_sign_wait_signs_sent,"[sign, wait, signs, sent, lord, allah able, pe...",[and they say why has a sign not been sent dow...
32,31,6,31_ally_excellent_protector_companions,"[ally, excellent, protector, companions, darkn...",[and whoever obeys allah and the messenger tho...
33,32,6,32_whoever allah_laid_sends astray_allah guides,"[whoever allah, laid, sends astray, allah guid...",[whoever allah sends astray there is no guide ...
34,33,6,33_book allah_allah exalted_exalted might_migh...,"[book allah, allah exalted, exalted might, mig...",[the revelation of the book is from allah the ...
35,34,5,34_way allah_established way_way_established,"[way allah, established way, way, established,...",[there is not to be upon the prophet any disco...
36,35,5,35_abraham_abraham said_said_father,"[abraham, abraham said, said, father, disassoc...",[and mention o muhammad when abraham said to h...

In [7]:

new_sub_topics = sub_topic_model.reduce_outliers(documents = sub_cluster_docs, topics = sub_topics, strategy="c-tf-idf")

# You MUST run this step to update the model's internal representations
sub_topic_model.update_topics(sub_cluster_docs, topics = new_sub_topics, vectorizer_model = vectorizer)

print("Outliers successfully reduced and reassigned using the c-TF-IDF strategy.")
print("\nUpdated Topic Information:")
# Check the count of the -1 topic to verify the reduction
(sub_topic_model.get_topic_info())

2025-12-05 04:53:59,754 - BERTopic - WARNING: Using a custom list of topic assignments may lead to errors if topic reduction techniques are used afterwards. Make sure that manually assigning topics is the last step in the pipeline.Note that topic embeddings will also be created through weightedc-TF-IDF embeddings instead of centroid embeddings.

Outliers successfully reduced and reassigned using the c-TF-IDF strategy.

Updated Topic Information:

,Topic,Count,Name,Representation,Representative_Docs
0,0,119,0_punishment_disbelieved_never_disbelievers,"[punishment, disbelieved, never, disbelievers,...",[those who disbelieved and averted others from...
1,1,82,1_merciful_forgiving_forgiving merciful_allah ...,"[merciful, forgiving, forgiving merciful, alla...",[except for those who repent after that and co...
2,2,67,2_believed_prayer_let_fear,"[believed, prayer, let, fear, fear allah, may,...",[o you who have believed be persistently stand...
3,3,59,3_quran_muhammad_revealed_sent,"[quran, muhammad, revealed, sent, verses, book...",[alif lam ra this is a book which we have reve...
4,4,36,4_besides_worship_besides allah_commanded,"[besides, worship, besides allah, commanded, p...",[you only worship besides allah idols and you ...
5,5,24,5_created_allah created_creation_earth,"[created, allah created, creation, earth, sky,...",[have you not seen that allah created the heav...
6,6,29,6_messenger_turn away_away_notification,"[messenger, turn away, away, notification, tur...",[and obey allah and obey the messenger but if ...
7,7,18,7_hypocrites_messenger_surely_party,"[hypocrites, messenger, surely, party, turns, ...",[and there are those hypocrites who took for t...
8,8,29,8_said_mention_mary_wife,"[said, mention, mary, wife, said lord, allah s...",[mention o muhammad when the wife of imran sai...
9,9,17,9_fear allah_fear_allah obey_obey,"[fear allah, fear, allah obey, obey, treat, ra...","[so fear allah and obey me, so fear allah and ..."
10,10,18,10_gardens_rivers flow_flow_beneath,"[gardens, rivers flow, flow, beneath, beneath ...",[indeed allah will admit those who believe and...
11,11,14,11_deity_allah deity_exalted allah_call,"[deity, allah deity, exalted allah, call, exal...",[allah there is no deity except him the ever l...
12,12,13,12_straight_path_straight path_lord lord,"[straight, path, straight path, lord lord, lor...",[jesus said and indeed allah is my lord and yo...
13,13,18,13_reward_spend_wealth_spent,"[reward, spend, wealth, spent, reward lord, go...",[so allah gave them the reward of this world a...
14,14,15,14_chosen_servants allah_exalted_allah powerful,"[chosen, servants allah, exalted, allah powerf...","[but not the chosen servants of allah, but not..."
15,15,27,15_heavens_heavens earth_belongs_belongs heavens,"[heavens, heavens earth, belongs, belongs heav...",[whatever is in the heavens and earth exalts a...
16,16,16,16_rain_see allah_night_sends,"[rain, see allah, night, sends, sky, see, ligh...",[and in the alternation of night and day and i...
17,17,12,17_fears_joseph_superior_fear,"[fears, joseph, superior, fear, fear allah, sa...","[he who fears allah will be reminded, as for h..."
18,18,19,18_spend_worldly life_worldly_enjoyment,"[spend, worldly life, worldly, enjoyment, life...",[charity is for the poor who have been restric...
19,19,15,19_matter_test_breasts_killed,"[matter, test, breasts, killed, threw, within ...",[and you did not kill them but it was allah wh...
20,20,14,20_allies_fight_take_perhaps,"[allies, fight, take, perhaps, jews, believers...",[so fight o muhammad in the cause of allah you...
21,21,17,21_hour_respond_gathered_resurrect,"[hour, respond, gathered, resurrect, allah res...",[only those who hear will respond but the dead...
22,22,16,22_messengers_sent messengers_sent_certainly,"[messengers, sent messengers, sent, certainly,...",[and we have already sent messengers before yo...
23,23,13,23_warner_muhammad_warn_bringer,"[warner, muhammad, warn, bringer, remind, tidi...","[so remind o muhammad you are only a reminder,..."
24,24,12,24_brother_people worship_said fear_allah deity,"[brother, people worship, said fear, allah dei...",[and to thamud we sent their brother salih he ...
25,25,12,25_unjust_lie_denies_hands put,"[unjust, lie, denies, hands put, put forth, ha...",[and who is more unjust than one who invents a...
26,26,9,26_grieve_concerning grieve_fear concerning_he...,"[grieve, concerning grieve, fear concerning, h...",[unquestionably for the allies of allah there ...
27,27,12,27_created_day resurrection_strength_resurrection,"[created, day resurrection, strength, resurrec...",[allah is the one who created you from weaknes...
28,28,8,28_victory_give_gain_need,"[victory, give, gain, need, victory allah, nee...",[and whoever of you devoutly obeys allah and h...
29,29,9,29_said_said seek_said people_refuge allah,"[said, said seek, said people, refuge allah, a...",[he said o my people have you considered if i ...
30,30,10,30_sign_signs_allah willed_willed,"[sign, signs, allah willed, willed, clear, oth...",[and they say why has a sign not been sent dow...
31,31,9,31_ally_excellent_sufficient allah_sufficient,"[ally, excellent, sufficient allah, sufficient...",[and whoever obeys allah and the messenger tho...
32,32,15,32_astray_guide_sends astray_whoever,"[astray, guide, sends astray, whoever, astray ...",[whoever allah sends astray there is no guide ...
33,33,10,33_allah exalted_might wise_exalted might_wise,"[allah exalted, might wise, exalted might, wis...",[the revelation of the book is from allah the ...
34,34,8,34_change_way allah_established way_way,"[change, way allah, established way, way, esta...",[there is not to be upon the prophet any disco...
35,35,7,35_abraham_said_disassociated_father,"[abraham, said, disassociated, father, allah s...",[and mention o muhammad when abraham said to h...

In [9]:
SUB_TARGET_TOPIC_ID = 0  # pick a sub-topic from Level 1
sub_target_indices = [i for i, t in enumerate(sub_topics) if t == SUB_TARGET_TOPIC_ID]
sub_sub_cluster_docs = [sub_cluster_docs[i] for i in sub_target_indices]

print(f"Level 2: Number of docs in Sub-Topic {SUB_TARGET_TOPIC_ID} = {len(sub_sub_cluster_docs)}")

# --- Level 2: sub-sub-cluster ---
sub_sub_topic_model = BERTopic(
    embedding_model=embedding_model,
    vectorizer_model=vectorizer,
    umap_model=umap_model,
    hdbscan_model=hdbscan_model,
    nr_topics="auto"
)

sub_sub_topics, sub_sub_probs = sub_sub_topic_model.fit_transform(sub_sub_cluster_docs)
sub_sub_topic_model.get_topic_info()

Level 2: Number of docs in Sub-Topic 0 = 102

,Topic,Count,Name,Representation,Representative_Docs
0,-1,28,-1_lord_punishment_said_taken,"[lord, punishment, said, taken, disbelievers, ...",[so let not their wealth or their children imp...
1,0,16,0_people_revealed_way allah_way,"[people, revealed, way allah, way, sins, avert...",[they took their false oaths as a cover so the...
2,1,13,1_punishment_cursed_allah messenger_messenger,"[punishment, cursed, allah messenger, messenge...",[allah has promised the hypocrite men and hypo...
3,2,11,2_believe_believe allah_came_assumption,"[believe, believe allah, came, assumption, ass...",[and they swear by allah their strongest oaths...
4,3,8,3_land_secure_earth_come,"[land, secure, earth, come, allah one, power, ...",[have they not traveled through the land and s...
5,4,7,4_fire_disbelieve_never_appease,"[fire, disbelieve, never, appease, fire abide,...",[it is not for the polytheists to maintain the...
6,5,7,5_let_kill_punish_world,"[let, kill, punish, world, punishment, behind,...",[and let those executors and guardians fear in...
7,6,7,6_allah allah_sight_behind_equal,"[allah allah, sight, behind, equal, equal alla...",[descendants some of them from others and alla...
8,7,5,7_never_faith_disbelief_whoever,"[never, faith, disbelief, whoever, never harm,...",[indeed those who disbelieve and commit wrong ...

In [11]:

new_sub_sub_topics = sub_sub_topic_model.reduce_outliers(documents = sub_sub_cluster_docs, topics = sub_sub_topics, strategy="c-tf-idf")

# You MUST run this step to update the model's internal representations
sub_sub_topic_model.update_topics(sub_sub_cluster_docs, topics = new_sub_sub_topics, vectorizer_model = vectorizer)

print("Outliers successfully reduced and reassigned using the c-TF-IDF strategy.")
print("\nUpdated Topic Information:")
# Check the count of the -1 topic to verify the reduction
(sub_sub_topic_model.get_topic_info())

2025-12-05 04:55:23,368 - BERTopic - WARNING: Using a custom list of topic assignments may lead to errors if topic reduction techniques are used afterwards. Make sure that manually assigning topics is the last step in the pipeline.Note that topic embeddings will also be created through weightedc-TF-IDF embeddings instead of centroid embeddings.

Outliers successfully reduced and reassigned using the c-TF-IDF strategy.

Updated Topic Information:

,Topic,Count,Name,Representation,Representative_Docs
0,0,22,0_people_way allah_taken_way,"[people, way allah, taken, way, deeds, wrath, ...",[they took their false oaths as a cover so the...
1,1,17,1_punishment_hell_whoever_messenger,"[punishment, hell, whoever, messenger, abide, ...",[allah has promised the hypocrite men and hypo...
2,2,16,2_believe_came_knowing_day,"[believe, came, knowing, day, lord, said, assu...",[and they swear by allah their strongest oaths...
3,3,11,3_land_come_said_secure,"[land, come, said, secure, earth, even, allah ...",[have they not traveled through the land and s...
4,4,9,4_fire_disbelieve_never_fire abide,"[fire, disbelieve, never, fire abide, wealth, ...",[it is not for the polytheists to maintain the...
5,5,10,5_let_punish_disbelievers_allah intends,"[let, punish, disbelievers, allah intends, int...",[and let those executors and guardians fear in...
6,6,8,6_another_allah another_another deity_deity,"[another, allah another, another deity, deity,...",[descendants some of them from others and alla...
7,7,9,7_never_painful_disbelief_painful punishment,"[never, painful, disbelief, painful punishment...",[indeed those who disbelieve and commit wrong ...